const DAYCARE_DATA = [
    {
        id: 1,
        region: 'Coquitlam',
        name: 'Acclaim Canada Education & Family Childcare Services',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Sara Nasir',
        address: '1104 Charland Ave, Coquitlam',
        phoneNumber: '(604) 562-2273',
        google: '',
        FHreport: '2 complaints',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=5CFE3AAB0C5D743D8825848C007E48A8',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1104+Charland+Ave%2C+Coquitlam%2C+BC+V3K3L1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=GlJ8eaAFrEfYNvVs4gqpdm0yIu8=',
    },
    {
        id: 2,
        region: 'Coquitlam',
        name: 'Allegro Musical Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Arellano Contreras Nairy de los Angeles',
        address: '3143 Sechelt Dr, Coquitlam',
        phoneNumber: '(778) 288-5484',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=8E0813CE66A572FF882587DB005F2275',
        image: 'https://lh3.googleusercontent.com/p/AF1QipOJAnR0r58Nva6U11OFGmjQLZOL50Jbqu5Cj62_=s680-w680-h510',
    },
    {
        id: 3,
        region: 'Coquitlam',
        name: 'Brilliant Star Family Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Nayyer Maghsoodi',
        address: '798 Dalip Crt, Coquitlam',
        phoneNumber: '(604) 931-5753',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=84B9CF7C29BE41EA882577EB0069BE3B',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=798+Dalip+Ct%2C+Coquitlam%2C+BC+V3J7Y3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=3X5UziFxOq2kX5JgJN2O8a9H5K4=',
    },
    {
        id: 4,
        region: 'Coquitlam',
        name: 'Bumble Bear Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Alexis Kelli Stobie',
        address: '3093 Mulberry Pl, Coquitlam',
        phoneNumber: '(604) 944-9807',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=A9FD053426D71D73882578110071D2C8',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=748&ImageOrder=1',
    },
    {
        id: 5,
        region: 'Coquitlam',
        name: `Bunny's Childcare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Gina Dragica Lovric',
        address: '1060 Rochester Ave, Coquitlam',
        phoneNumber: '(604) 939-2517',
        google: '',
        FHreport: '1 complaint/1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=42AAA667D5FEE66A8825764100558FC5',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMOQYubGZhDu071wLHAbt7ALyLDtWvVFsC_M1i_=s680-w680-h510',
    },
    {
        id: 6,
        region: 'Coquitlam',
        name: 'Cherry Blossom Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Karyna Ryzhkova',
        address: '3154 Bowen Dr, Coquitlam',
        phoneNumber: '(604) 551-3206',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=A69C23451C2F02B5882589B000601E20',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3154+Bowen+Dr%2C+Coquitlam%2C+BC+V3B5S7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=FZ19khd3CzM2uGSCAIqxxC9qNgo=',
    },
    {
        id: 7,
        region: 'Coquitlam',
        name: 'Claydon Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Tracey Claydon',
        address: '3200 Harwood Ave, Coquitlam',
        phoneNumber: '(604) 838-6855',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=098884B7A2A9C22788256D2700704CCD',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3200+Harwood+Ave%2C+Coquitlam%2C+BC+V3E1P3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=yJYY_q6YG-8A2X7rVZk5ag_knuk=',
    },
    {
        id: 8,
        region: 'Coquitlam',
        name: `Denise's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Denise Palmer',
        address: '951 Shiloh Ct, Coquitlam',
        phoneNumber: '(604) 552-9760',
        google: '',
        FHreport: '',
        FHreportUrl: '',
        image: 'https://photos.zillowstatic.com/fp/a114477799572472b21aa4097580db25-cc_ft_768.webp',
    },
    {
        id: 9,
        region: 'Coquitlam',
        name: 'Dream Tree Day Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Choon Hee Jeun',
        address: '2405 King Albert Ave, Coquitlam',
        phoneNumber: '(604) 936-9948',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D620C6F852E52FFF882572C30054494A',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2405+King+Albert+Ave%2C+Coquitlam%2C+BC+V3J7E6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=OGlSf8VIsIcWA3nkVjm1LPX9iRE=',
    },
    {
        id: 10,
        region: 'Coquitlam',
        name: `Fav's Kangaroos Family Home Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lerida Faviola Schilling',
        address: '3250 Samuels Ct, Coquitlam',
        phoneNumber: '(604) 346-8066',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=87AFA6570FE2841388257FF5006C5F2C',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMSOKRwNNUh00jBmci_pAQNivxAVHwbTwXWHwOK=s680-w680-h510',
    },
    {
        id: 11,
        region: 'Coquitlam',
        name: 'FunTime Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Asmin Sharif',
        address: '1898 Brunette Ave, Coquitlam',
        phoneNumber: '(778) 838-8258',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=DDE096B56FAD316A88257DB30001DB57',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1898+Brunette+Ave%2C+Coquitlam%2C+BC+V3K1H2&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=RcqU3EOa50pS4mftBq9YNfz6eRQ=',
    },
    {
        id: 12,
        region: 'Coquitlam',
        name: 'Gamesters Gift of Time',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lottie Jane Gamester',
        address: '1704 Sheridan Ave, Coquitlam',
        phoneNumber: '(778) 227-4335',
        google: '',
        FHreport: '1 complaint',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=3B2B6CFDA1938A1F88257CA50074989E',
        image: 'https://propimages.bcassessment.ca/10/305/08300001/thumbnail.jpg',
    },
    {
        id: 13,
        region: 'Coquitlam',
        name: 'Happy Steps Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Millie Liu',
        address: '2045 Kugler Ave, Coquitlam',
        phoneNumber: '(778) 355-5288',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=2B25663E64CE2BCC88257A68005A7137',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2045+Kugler+Ave%2C+Coquitlam%2C+BC+V3K2S5&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=kB2yjoTBa2QJwFDsmd8TeL57oNQ=',
    },
    {
        id: 14,
        region: 'Coquitlam',
        name: 'Holly Hobby House Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Brigitte Guilbault',
        address: '5 - 2880 Dacre Ave, Coquitlam',
        phoneNumber: '(604) 552-4000',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=14FC6FFE98BC501788256D2700704C94',
        image: 'https://iss-cdn.myrealpage.com/vMdDl6dYOF1GBZWiyRY9TYZm2YdnB3l9HfHjUuhFeho/rs:auto:0:0:0/g:sm/aHR0cDovL3MzLmFtYXpvbmF3cy5jb20vbXJwLWxpc3RpbmdzLzIvNi83LzQ5Mjc3NjIvNTg5YzI2YjhiZmZkMjVhYWNlNjY4ODBlMGMwNjUxYzcuanBlZw',
    },
    {
        id: 15,
        region: 'Coquitlam',
        name: `Jane's Happy Family Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shujie Dong',
        address: '#1 - 2865 Glen Dr, Coquitlam',
        phoneNumber: '(604) 307-9219',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=60B4CF8DA1C5EE5A88256D2700704E0D',
        image: 'https://lh3.googleusercontent.com/p/AF1QipNdViKRUllUIQTxsrWCw_4Dz61Yv1evOMMg0MA3=s680-w680-h510',
    },
    {
        id: 16,
        region: 'Coquitlam',
        name: 'Jax and Friends Playcare Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Cindy Gail Smith',
        address: '2283 Stanwood Ave, Coquitlam',
        phoneNumber: '(778) 891-1517',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=2C1AF597A0ECBBFF882583360063D371',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2283+Stanwood+Ave%2C+Coquitlam%2C+BC+V3K3A7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=SHZZkrV_eMYi2Ar5Dk2rqOrIRRk=',
    },
    {
        id: 17,
        region: 'Coquitlam',
        name: 'Jia Jia Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Xu Yan Zhang',
        address: '3014 Delahaye Dr, Coquitlam',
        phoneNumber: '(604) 475-2663',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=6EECD60037BC47BF8825773F007E353A',
        image: 'https://maps.googleapis.com/maps/api/streetview?channel=mb-ldp-publicrecord&location=3014+Delahaye+Dr%2C+Coquitlam%2C+BC+V3B+6V8&size=665x441&source=outdoor&client=gme-redfin&signature=QAutCMu3u8O70gKvupyU4a25v2w=',
    },
    {
        id: 18,
        region: 'Coquitlam',
        name: 'Julie & Friends Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Julie Holmes',
        address: '755 Adiron Ave, Coquitlam',
        phoneNumber: '(604) 931-9045',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=465A1885729C0B1A88256D2700704DE8',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=755+Adiron+Ave%2C+Coquitlam%2C+BC+V3J4K1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=YoiLl5jM0Zmc7uo9HXAGJlCsEO0=',
    },
    {
        id: 19,
        region: 'Coquitlam',
        name: 'Kinder Korner Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Christina Marie Windsor',
        address: '903 Dansey Ave, Coquitlam',
        phoneNumber: '(778) 707-0140',
        google: '',
        FHreport: '7 complaints/2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=78B2A644D3A3E4EA88257D470062B24E',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=903+Dansey+Ave%2C+Coquitlam%2C+BC+V3K3G6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=2E72Ot9_PX-BimND4LqSMb2vQy4=',
    },
    {
        id: 20,
        region: 'Coquitlam',
        name: 'Learning Steps Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Susmita Gupta',
        address: '1254 Johnson St, Coquitlam',
        phoneNumber: '(604) 725-6373',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=E6614C1D2A34B5178825827F00747068',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1254+Johnson+St%2C+Coquitlam%2C+BC+V3B4T4&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=l7Zd62DzE5mGxgRObGQ9EqBuTow=',
    },
    {
        id: 21,
        region: 'Coquitlam',
        name: 'Little Bloomers',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Debbie Bruce',
        address: '#11 - 1383 Brunette Ave, Coquitlam',
        phoneNumber: '(604) 727-2206',
        google: '',
        FHreport: '1 complaint',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=F4E241B0F905FF7B88256D2700704D4F',
        image: 'https://lh3.googleusercontent.com/p/AF1QipOKidH4fCm_VEdt3R4Hx8gQycBRyyc4IvMFXD8P=s680-w680-h510',
    },
    {
        id: 22,
        region: 'Coquitlam',
        name: 'Little Friend Circles Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Seemi Waheed',
        address: '1346 El Camino Dr, Coquitlam',
        phoneNumber: '(604) 944-8658',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=7938568E03E4F2C088258271006EDBC3',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1346+El+Camino+Dr%2C+Coquitlam%2C+BC+V3E2P8&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=oReubi0wTLW6lkxtYlVinds66Oc=',
    },
    {
        id: 23,
        region: 'Coquitlam',
        name: 'Little Sparrows Day Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Rose Chequer',
        address: '1014 Quadling Ave, Coquitlam',
        phoneNumber: '(604) 603-1146',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=31D4B937DB570B868825816F0062606F',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMfTO-uEFusK45clxxx3x9Qr9KFMmx1kYF1PboE=s680-w680-h510',
    },
    {
        id: 24,
        region: 'Coquitlam',
        name: 'Little Stars Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Anna Morgan',
        address: '2746 Westlake Dr, Coquitlam',
        phoneNumber: '(604) 767-9137',
        google: '5/5 (1 review)',
        FHreport: 'No complaints/inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=9A1E21115D36D4B5882574A3005FD25F',
        image: 'https://lh3.googleusercontent.com/p/AF1QipPyxZCWO6E8E39J_tfhjInWY0K4HrNSMk4hpeNO=s2880-w2880-h1712-rw',
    },
    {
        id: 25,
        region: 'Coquitlam',
        name: `McBay's Family Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Brenda McBay',
        address: '2100 Lyons Court, Coquitlam',
        phoneNumber: '(604) 931-4037',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=7E0EC257F327338D88256FE4005AAA56',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2100+Lyons+Ct%2C+Coquitlam%2C+BC+V3J3L7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=8GF0P-aLrrRpTFhupI3LadHddT0=',
    },
    {
        id: 26,
        region: 'Coquitlam',
        name: 'Meme Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Rukmanie S. Gunaratna',
        address: '3495 David Ave, Coquitlam',
        phoneNumber: '(604) 355-1702',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=EE1BD517EC711B3A88258601007121FD',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3495+David+Ave%2C+Coquitlam%2C+BC+V3E0H7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=GdDqCVWbOomkjls7ZjCwzFkVPKM=',
    },
    {
        id: 27,
        region: 'Coquitlam',
        name: 'Pitter Patter Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Michele Bosa',
        address: '1267 Nestor St, Coquitlam',
        phoneNumber: '(604) 626-3952',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=13B51A27C2B31B2E88257871005755B7',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=_waP_yJXcnijSr7DPm9vag&cb_client=search.gws-prod.gps&w=408&h=240&yaw=80.08875&pitch=0&thumbfov=100',
    },
    {
        id: 28,
        region: 'Coquitlam',
        name: 'Plateau Montessori Childcare',
        type: 'Family Child Care',
        maxCap: 8,
        owner: 'Parvin Gharehkhani',
        address: '3285 Plateau Blvd, Coquitlam',
        phoneNumber: '(604) 916-9592',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=C2E5D484FDCC64CC88258934007FCF24',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3285+Plateau+Blvd%2C+Coquitlam%2C+BC+V3E3B8&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=dHNXPd_VmEn_8HEgNP5LuO3ZPBs=',
    },
    {
        id: 29,
        region: 'Coquitlam',
        name: 'Playcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lana Fedoruk',
        address: '517 Appian Way, Coquitlam',
        phoneNumber: '(604) 939-9142',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D8919A0160C6F71288256D2700704CD5',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=517+Appian+Way%2C+Coquitlam%2C+BC+V3J2A6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=hT-0zfe8I_hiZ0g7Lp25DqNwpYQ=',
    },
    {
        id: 30,
        region: 'Coquitlam',
        name: 'Precious Shepherd Family Daycare',
        type: 'Family Child Care',
        maxCap: 6,
        owner: 'Mary Jane B. Narag',
        address: '850 Greene St, Coquitlam',
        phoneNumber: '(604) 322-9766',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=40AE86686BC0662B88257A610078BB37',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=UQ710Kurebh3oz7UQRHg4w&cb_client=search.gws-prod.gps&w=408&h=240&yaw=332.2726&pitch=0&thumbfov=100',
    },
    {
        id: 31,
        region: 'Coquitlam',
        name: 'Raindrops Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Maria Salvati',
        address: '3216 Harwood Ave, Coquitlam',
        phoneNumber: '(604) 941-6123',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=7865D861424E695F88256D2700704C1B',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3216+Harwood+Ave%2C+Coquitlam%2C+BC+V3E1T8&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=VpTC0dF0TgZl7IQLQAYUkI3wEn0=',
    },
    {
        id: 32,
        region: 'Coquitlam',
        name: 'Stars Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shala Monfred',
        address: '1713 Sugarpine Ct, Coquitlam',
        phoneNumber: '(604) 945-9416',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=28AD7C17C65F1D9C88256D2700704CB9',
        image: 'https://starschildcare.ca/starschildcare-wp/wp-content/uploads/2012/08/stars-childcare-home1.jpg',
    },
    {
        id: 33,
        region: 'Coquitlam',
        name: 'Sunshine Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Fatemeh Varestesvishgahi',
        address: '#1111 - 550 Cottonwood Ave, Coquitlam',
        phoneNumber: '(604) 937-3578',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=A88B9FA205287D4888256D2700704D94',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=Tur4Yr3b-tpdlHuyX-L7KA&cb_client=search.gws-prod.gps&w=408&h=240&yaw=159.13132&pitch=0&thumbfov=100',
    },
    {
        id: 34,
        region: 'Coquitlam',
        name: 'Supreme Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Audrey Clarke',
        address: '701 Hailey Street, Coquitlam',
        phoneNumber: '(604) 936-4827',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=92083DD4BCA39B488825724A0080A144',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=701+Hailey+St%2C+Coquitlam%2C+BC+V3J4N7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=5t2QyaXNfQgYPw5iFcOjTM2O1HU=',
    },
    {
        id: 35,
        region: 'Coquitlam',
        name: 'Sweet Peas Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Carmen Ricci',
        address: '1889 Bluff Way, Coquitlam',
        phoneNumber: '(604) 765-3576',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=B40D71B1639A038E882584200061B383',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1889+Bluff+Way%2C+Coquitlam%2C+BC+V3E1J3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=OMPHY2arpeCwFS9nqGz7furNhXc=',
    },
    {
        id: 36,
        region: 'Coquitlam',
        name: `Sweet Pea's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Sonia M. Rodrigues',
        address: '699 Accacia Ave, Coquitlam',
        phoneNumber: '(778) 707-2634',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D65205FE096854528825806400693A34',
        image: 'https://scontent.fyvr1-1.fna.fbcdn.net/v/t39.30808-6/305757192_592086369082646_4514146418651981471_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=52f669&_nc_ohc=SnluZuvkavkAX-zSy_v&_nc_ht=scontent.fyvr1-1.fna&oh=00_AfB33AD71sJJJHzDl5D5dTBe15EqUJDepSUXM03iiemdSA&oe=652696D8',
    },
    {
        id: 37,
        region: 'Coquitlam',
        name: 'Wonderland Plateau Daycare',
        type: 'Family Child Care',
        maxCap: 8,
        owner: 'Fariba Kaheh',
        address: '3066 Sienna Ct, Coquitlam',
        phoneNumber: '(604) 318-1479',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=F23A5F66D4BE04428825841E006F9DB4',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3066+Sienna+Ct%2C+Coquitlam%2C+BC+V3E3N7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=kyR9BpTyi1anlsIADshZNMl4rOw=',
    },
    {
        id: 38,
        region: 'Maple Ridge',
        name: 'ABC Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Gina Donkin',
        address: '11633 232A St Maple Ridge, V2X 2K5',
        phoneNumber: '(604) 240-9046',
        google: '',
        FHreport: '3 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=39A7929A110E637888257669007D350D',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=-JvUNFTZ22c7Zqmj5cQC4g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=227.87242&pitch=0&thumbfov=100',
    },
    {
        id: 39,
        region: 'Maple Ridge',
        name: 'Albion Good Beginnings',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Mona Lechintan',
        address: '24020 102nd Ave Maple Ridge, V2W 1J1',
        phoneNumber: '(604) 356-7070',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=E4A07D34D257E63B88257CE6006648EB',
        image: 'https://lh3.googleusercontent.com/p/AF1QipO5YBl30rCIhOv5grZGXtzd9wnfYKJexsPqL4N4=s680-w680-h510',
    },
    {
        id: 40,
        region: 'Maple Ridge',
        name: 'Basket Of Joy',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Blanca Walters',
        address: '12510 223rd St Maple Ridge, V2X 5Z1',
        phoneNumber: '(604) 467-2053',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=CC6988D3EFEB05CB88256D2700704CAB',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=1ew_NMjoc-etVwAx-M8oRg&cb_client=search.gws-prod.gps&w=408&h=240&yaw=67.51511&pitch=0&thumbfov=100',
    },
    {
        id: 41,
        region: 'Maple Ridge',
        name: 'Bright Beginnings Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lynn Brant',
        address: '12030 232B St Maple Ridge, V2X 0X1',
        phoneNumber: '(604) 313-9417',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=C1F96B6C5BFEFEDE88256D2700704CB1',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=23850+117b+Ave%2C+Maple+Ridge%2C+BC+V4R2V6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=lnUriipB5Uv3RJUMeIXR5jyrkMI=',
    },
    {
        id: 42,
        region: 'Maple Ridge',
        name: 'Circle Time Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Stephanie Kwasnica',
        address: '12285 212th St Maple Ridge, V4R 2V6',
        phoneNumber: '(604) 463-3728',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=C1F96B6C5BFEFEDE88256D2700704CB1',
        image: 'https://images.squarespace-cdn.com/content/v1/5ff6a7c667a5a02a5d52766e/1610849404288-4YE7IP1CC5VMTA9OPC07/MB2_1683.JPG?format=1000w',
    },
    {
        id: 42,
        region: 'Maple Ridge',
        name: `Doodle's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Jennifer Briggs',
        address: '11870 236th St Maple Ridge, V4R 2E1',
        phoneNumber: '(604) 466-2705',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=4E4BED57689E2199882572C900783F18',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=11870+236th+St%2C+Maple+Ridge%2C+BC+V4R2E1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=YluikysZ3AoaES99yGKyTpkQJ0I=',
    },
    {
        id: 43,
        region: 'Maple Ridge',
        name: 'Happy Sky Daycare Centre',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Su Chen Liao (Skye)',
        address: '11670 Miller St Maple Ridge, V2X 9M6',
        phoneNumber: '(778) 822-5228',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=6A44E42E29B25DC08825847400738627',
        image: 'https://lh3.googleusercontent.com/p/AF1QipOIhNlaw8XFAz1qZcwVr8jGWRxMFFEWEPigagbl=s680-w680-h510',
    },
    {
        id: 44,
        region: 'Maple Ridge',
        name: `Hilda's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Hilda Hoyes',
        address: '12741 226th St Maple Ridge, V2X 6H6',
        phoneNumber: '(604) 463-7889',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=6AD9F7EDB7B2579488256D2700704C70',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=12741+226th+St%2C+Maple+Ridge%2C+BC+V2X6H6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=sOrC4vsgNWpjPCZstjNrdoXEhdo=',
    },
    {
        id: 45,
        region: 'Maple Ridge',
        name: 'Home Sweet Home',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shiva Isapour',
        address: '23668 Kanaka Way Maple Ridge, V2W 2A1',
        phoneNumber: '(778) 927-4425',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=BC989E3AD7A718C5882582F6007712EB',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=23668+Kanaka+Way%2C+Maple+Ridge%2C+BC+V2W2A1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=Ohw60Zd-QsBiVf4O5tsvofi65RQ=',
    },
    {
        id: 46,
        region: 'Maple Ridge',
        name: 'Hugs and Cuddles Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Susan Steimer',
        address: '12545 223rd St Maple Ridge, V2X 5Y8',
        phoneNumber: '(604) 466-5900',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=B94C300275A95AC78825740800700A2D',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=12545+223rd+St%2C+Maple+Ridge%2C+BC+V2X5Y8&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=B_mcdt9q1eEQn3TAVXiFu5brz2I=',
    },
    {
        id: 47,
        region: 'Maple Ridge',
        name: 'Jackson Ridge Kids Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Susan Steimer',
        address: '10074 246B St Maple Ridge, V2W 0H1',
        phoneNumber: '(604) 380-0707',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D3D14F138DF914E588257D9D0071281D',
        image: 'https://lh3.googleusercontent.com/p/AF1QipNL_FwPANJej1zvekfWnPFX663dRussCMrjh_8N=s680-w680-h510',
    },
    {
        id: 48,
        region: 'Maple Ridge',
        name: `Joanne's House`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Joanne Hemmerling',
        address: '20516 123B Ave Maple Ridge, V2X 0L9',
        phoneNumber: '(604) 465-9759',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=CD328409A9601A9088256D2700704C60',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=20516+123b+Ave%2C+Maple+Ridge%2C+BC+V2X0L9&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=cgfYJoTR2EzKinywo_nCoREkMGc=',
    },
    {
        id: 49,
        region: 'Maple Ridge',
        name: `Julie's Whippersnappers`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Julie Shay',
        address: '12314 Fletcher St Maple Ridge, V2X 6K9',
        phoneNumber: '(604) 785-9419',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D7FA205B8A1B362588257FC50065A305',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=2haZL464f65aR4zLa3OIIQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=107.434494&pitch=0&thumbfov=100',
    },
    {
        id: 50,
        region: 'Maple Ridge',
        name: 'Junior Explorers Academy',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Vanessa Vincente',
        address: '24002 McClure Dr Maple Ridge, V2W 1Z3',
        phoneNumber: '(778) 986-6283',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=17822B6ECF4A7E4D8825864200820D44',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=y9hKXtKdEMfwejF64dn_7w&cb_client=search.gws-prod.gps&w=408&h=240&yaw=114.33159&pitch=0&thumbfov=100',
    },
    {
        id: 51,
        region: 'Maple Ridge',
        name: 'Kiddo & Co. Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Julia Boutin',
        address: '24331 104th Ave Maple Ridge, V2W 0G7',
        phoneNumber: '(604) 218-8586',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=5F6C0953957E1844882585A0006D6ED4',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=24331+104th+Ave%2C+Maple+Ridge%2C+BC+V2W0G7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=6DJy8_TFzDNZkqQAHNjeMBvUvEw=',
    },
    {
        id: 52,
        region: 'Maple Ridge',
        name: 'Lambchops Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shelley Stewart',
        address: '21179 Douglas Ave Maple Ridge, V4R 2H7',
        phoneNumber: '(604) 467-8492',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=E31AB33CC4EE1E9C88256D2700704E05',
        image: 'https://static.wixstatic.com/media/788f45_b267ee7f8eb04834b8672d4d90be65f8~mv2.png/v1/fill/w_940,h_530,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/788f45_b267ee7f8eb04834b8672d4d90be65f8~mv2.png',
    },
    {
        id: 53,
        region: 'Maple Ridge',
        name: 'Lil Charlie Browns Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Tamara Delorme',
        address: '13822 232A St Maple Ridge, V4R 0C2',
        phoneNumber: '(604) 710-6540',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=79E1F6D97B241C2E88257B8E007CA410',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=13822+232a+St%2C+Maple+Ridge%2C+BC+V4R0C2&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=F1WCX3odgiO7v7UQNzaxBKDlEmw=',
    },
    {
        id: 54,
        region: 'Maple Ridge',
        name: 'Little Crayons Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Diane Formosa',
        address: '20770 123B Ave Maple Ridge, V2X 1M4',
        phoneNumber: '(604) 467-2249',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=CBBD9E7B0A23F27788256D2700704D01',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=16827&ImageOrder=5',
    },
    {
        id: 55,
        region: 'Maple Ridge',
        name: `Mee Wee's Corner Family Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Marie Victoria Karwath',
        address: '12628 215th St Maple Ridge, V3Z 1M9',
        phoneNumber: '(604) 463-5438',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=9648EF7526BB778588256D2700704C4E',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=13773&ImageOrder=9',
    },
    {
        id: 56,
        region: 'Maple Ridge',
        name: `Nana's Angels`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Kathy Mang',
        address: '11440 234A St Maple Ridge, V2W 1V6',
        phoneNumber: '(604) 463-9643',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=04AB04AFA6043E1788256D2700704D1C',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=k3yERf1f8STOTK0XalPxXQ&cb_client=search.gws-prod.gps&w=408&h=240&yaw=73.82408&pitch=0&thumbfov=100',
    },
    {
        id: 57,
        region: 'Maple Ridge',
        name: 'Ospring Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Jessie Resto',
        address: '20110 Ospring Street Maple Ridge, V2X 0G5',
        phoneNumber: '(604) 551-3401',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=EF3B8E08F7A1063D88257E910072B0C4',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=20110+Ospring+St%2C+Maple+Ridge%2C+BC+V2X0G5&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=QLmC4ooFUELbKfPVfxc2wAiB1wU=',
    },
    {
        id: 58,
        region: 'Maple Ridge',
        name: 'Playhouse Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lorie White',
        address: '11789 Glenhurst St Maple Ridge, V2X 9L4',
        phoneNumber: '(778) 239-4041',
        google: '',
        FHreport: '4 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=E6D78430E9EC279788257AB00060C04C',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=12953&ImageOrder=1',
    },
    {
        id: 59,
        region: 'Maple Ridge',
        name: 'Precious Tots Family Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Fungayi Mvundura',
        address: '12079 204B St Maple Ridge, V2X 1A9',
        phoneNumber: '(604) 603-8556',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/Clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=67EA8C62F1FE5BF08825813F00600802',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=20404&ImageOrder=1',
    },
    {
        id: 60,
        region: 'Maple Ridge',
        name: `Sandy's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Sandy Henry',
        address: '24859 106B St Maple Ridge, V2W 0E1',
        phoneNumber: '(604) 209-0165',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=07930C0D9F69BE9E8825818400704965',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=19845&ImageOrder=1',
    },
    {
        id: 61,
        region: 'Maple Ridge',
        name: `Smiles N' Hugs Family Child Care`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Teresita Dickson',
        address: '12294 Hillside St Maple Ridge, V2X 5X1',
        phoneNumber: '(604) 466-7393',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=6D028036A537DAEA8825740200760413',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=12294+Hillside+St%2C+Maple+Ridge%2C+BC+V2X5X1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=DVBzpxCc2t4jtaxSRZ4RpD9dToE=',
    },
    {
        id: 62,
        region: 'Maple Ridge',
        name: 'Sunrise Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Tatiana Lisnevskaya',
        address: '12221 210th St Maple Ridge, V2X 8B9',
        phoneNumber: '(778) 886-6525',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=6D028036A537DAEA8825740200760413',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=12221+210th+St%2C+Maple+Ridge%2C+BC+V2X8B9&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=64SaB-Kd4toTGmJmPh6oRcHOC-s=',
    },
    {
        id: 63,
        region: 'Maple Ridge',
        name: 'The Place to Grow',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Jessica Miller',
        address: '24272 102B Ave Maple Ridge, V2W 1Y1',
        phoneNumber: '(778) 927-4204',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=0AA78D84658C04BA8825835C0078164F',
        image: 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=KXl3xgmr9y3OVeGiu97O4g&cb_client=search.gws-prod.gps&w=408&h=240&yaw=178.02264&pitch=0&thumbfov=100',
    },
    {
        id: 64,
        region: 'Maple Ridge',
        name: 'Ultimate Care Nest Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shaghayegh (Sherry)Fannizadeh',
        address: '11724 209th St Maple Ridge, V2X 7S7',
        phoneNumber: '(604) 812-2482',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=037CCF01B0757E09882585C9005CE66D',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMoRygHw06oKFAjPT0VyT7KTcEALuGeJAWrxifP=s680-w680-h510',
    },
    {
        id: 65,
        region: 'Maple Ridge',
        name: 'Wilkinson Learning Tree',
        type: 'Family Child Care',
        maxCap: 7,
        owner: ' Christine Wilkinson',
        address: '10172 244th St Maple Ridge, V2W 0H5',
        phoneNumber: '(604) 537-2396',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=117990EFDDEC64AE8825843F0069D38B',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMkcCxu1lD-ebQGdyi4tsOetnjrW8TZdcHEK73F=s680-w680-h510',
    },
]

export default DAYCARE_DATA