const DAYCARE_DATA = [
    {
        id: 1,
        region: 'Coquitlam',
        name: 'Acclaim Canada Education & Family Childcare Services',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Sara Nasir',
        address: '1104 Charland Ave, Coquitlam',
        phoneNumber: '(604) 562-2273',
        google: '',
        FHreport: '2 complaints',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=5CFE3AAB0C5D743D8825848C007E48A8',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1104+Charland+Ave%2C+Coquitlam%2C+BC+V3K3L1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=GlJ8eaAFrEfYNvVs4gqpdm0yIu8=',
    },
    {
        id: 2,
        region: 'Coquitlam',
        name: 'Allegro Musical Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Arellano Contreras Nairy de los Angeles',
        address: '3143 Sechelt Dr, Coquitlam',
        phoneNumber: '(778) 288-5484',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=8E0813CE66A572FF882587DB005F2275',
        image: 'https://lh3.googleusercontent.com/p/AF1QipOJAnR0r58Nva6U11OFGmjQLZOL50Jbqu5Cj62_=s680-w680-h510',
    },
    {
        id: 3,
        region: 'Coquitlam',
        name: 'Brilliant Star Family Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Nayyer Maghsoodi',
        address: '798 Dalip Crt, Coquitlam',
        phoneNumber: '(604) 931-5753',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=84B9CF7C29BE41EA882577EB0069BE3B',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=798+Dalip+Ct%2C+Coquitlam%2C+BC+V3J7Y3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=3X5UziFxOq2kX5JgJN2O8a9H5K4=',
    },
    {
        id: 4,
        region: 'Coquitlam',
        name: 'Bumble Bear Childcare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Alexis Kelli Stobie',
        address: '3093 Mulberry Pl, Coquitlam',
        phoneNumber: '(604) 944-9807',
        google: '',
        FHreport: '1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=A9FD053426D71D73882578110071D2C8',
        image: 'http://www.daycarebear.ca/getimage.php?ListingID=748&ImageOrder=1',
    },
    {
        id: 5,
        region: 'Coquitlam',
        name: `Bunny's Childcare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Gina Dragica Lovric',
        address: '1060 Rochester Ave, Coquitlam',
        phoneNumber: '(604) 939-2517',
        google: '',
        FHreport: '1 complaint/1 follow-up inspection',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=42AAA667D5FEE66A8825764100558FC5',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMOQYubGZhDu071wLHAbt7ALyLDtWvVFsC_M1i_=s680-w680-h510',
    },
    {
        id: 6,
        region: 'Coquitlam',
        name: 'Cherry Blossom Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Karyna Ryzhkova',
        address: '3154 Bowen Dr, Coquitlam',
        phoneNumber: '(604) 551-3206',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=A69C23451C2F02B5882589B000601E20',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3154+Bowen+Dr%2C+Coquitlam%2C+BC+V3B5S7&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=FZ19khd3CzM2uGSCAIqxxC9qNgo=',
    },
    {
        id: 7,
        region: 'Coquitlam',
        name: 'Claydon Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Tracey Claydon',
        address: '3200 Harwood Ave, Coquitlam',
        phoneNumber: '(604) 838-6855',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=098884B7A2A9C22788256D2700704CCD',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=3200+Harwood+Ave%2C+Coquitlam%2C+BC+V3E1P3&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=yJYY_q6YG-8A2X7rVZk5ag_knuk=',
    },
    {
        id: 8,
        region: 'Coquitlam',
        name: `Denise's Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Denise Palmer',
        address: '951 Shiloh Ct, Coquitlam',
        phoneNumber: '(604) 552-9760',
        google: '',
        FHreport: '',
        FHreportUrl: '',
        image: 'https://photos.zillowstatic.com/fp/a114477799572472b21aa4097580db25-cc_ft_768.webp',
    },
    {
        id: 9,
        region: 'Coquitlam',
        name: 'Dream Tree Day Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Choon Hee Jeun',
        address: '2405 King Albert Ave, Coquitlam',
        phoneNumber: '(604) 936-9948',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=D620C6F852E52FFF882572C30054494A',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2405+King+Albert+Ave%2C+Coquitlam%2C+BC+V3J7E6&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=OGlSf8VIsIcWA3nkVjm1LPX9iRE=',
    },
    {
        id: 10,
        region: 'Coquitlam',
        name: `Fav's Kangaroos Family Home Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lerida Faviola Schilling',
        address: '3250 Samuels Ct, Coquitlam',
        phoneNumber: '(604) 346-8066',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=87AFA6570FE2841388257FF5006C5F2C',
        image: 'https://lh3.googleusercontent.com/p/AF1QipMSOKRwNNUh00jBmci_pAQNivxAVHwbTwXWHwOK=s680-w680-h510',
    },
    {
        id: 11,
        region: 'Coquitlam',
        name: 'FunTime Family Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Asmin Sharif',
        address: '1898 Brunette Ave, Coquitlam',
        phoneNumber: '(778) 838-8258',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=DDE096B56FAD316A88257DB30001DB57',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=1898+Brunette+Ave%2C+Coquitlam%2C+BC+V3K1H2&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=RcqU3EOa50pS4mftBq9YNfz6eRQ=',
    },
    {
        id: 12,
        region: 'Coquitlam',
        name: 'Gamesters Gift of Time',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Lottie Jane Gamester',
        address: '1704 Sheridan Ave, Coquitlam',
        phoneNumber: '(778) 227-4335',
        google: '',
        FHreport: '1 complaint',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=3B2B6CFDA1938A1F88257CA50074989E',
        image: 'https://propimages.bcassessment.ca/10/305/08300001/thumbnail.jpg',
    },
    {
        id: 13,
        region: 'Coquitlam',
        name: 'Happy Steps Daycare',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Millie Liu',
        address: '2045 Kugler Ave, Coquitlam',
        phoneNumber: '(778) 355-5288',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=2B25663E64CE2BCC88257A68005A7137',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=2045+Kugler+Ave%2C+Coquitlam%2C+BC+V3K2S5&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=kB2yjoTBa2QJwFDsmd8TeL57oNQ=',
    },
    {
        id: 14,
        region: 'Coquitlam',
        name: 'Holly Hobby House Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Brigitte Guilbault',
        address: '5 - 2880 Dacre Ave, Coquitlam',
        phoneNumber: '(604) 552-4000',
        google: '',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=14FC6FFE98BC501788256D2700704C94',
        image: 'https://iss-cdn.myrealpage.com/vMdDl6dYOF1GBZWiyRY9TYZm2YdnB3l9HfHjUuhFeho/rs:auto:0:0:0/g:sm/aHR0cDovL3MzLmFtYXpvbmF3cy5jb20vbXJwLWxpc3RpbmdzLzIvNi83LzQ5Mjc3NjIvNTg5YzI2YjhiZmZkMjVhYWNlNjY4ODBlMGMwNjUxYzcuanBlZw',
    },
    {
        id: 15,
        region: 'Coquitlam',
        name: `Jane's Happy Family Daycare`,
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Shujie Dong',
        address: '#1 - 2865 Glen Dr, Coquitlam',
        phoneNumber: '(604) 307-9219',
        google: '',
        FHreport: '2 follow-up inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=60B4CF8DA1C5EE5A88256D2700704E0D',
        image: 'https://lh3.googleusercontent.com/p/AF1QipNdViKRUllUIQTxsrWCw_4Dz61Yv1evOMMg0MA3=s680-w680-h510',
    },
    {
        id: 100,
        region: 'Coquitlam',
        name: 'Little Stars Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Anna Morgan',
        address: '2746 Westlake Dr, Coquitlam',
        phoneNumber: '(604) 767-9137',
        google: '5/5 (1 review)',
        FHreport: 'No complaints/inspections',
        FHreportUrl: 'https://www.healthspace.ca/clients/FHA/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=9A1E21115D36D4B5882574A3005FD25F',
        image: 'https://lh3.googleusercontent.com/p/AF1QipPyxZCWO6E8E39J_tfhjInWY0K4HrNSMk4hpeNO=s2880-w2880-h1712-rw',
    },
    {
        id: 200,
        region: 'Coquitlam',
        name: 'Julie & Friends Family Child Care',
        type: 'Family Child Care',
        maxCap: 7,
        owner: 'Julie Holmes',
        address: '755 Adiron Ave, Coquitlam',
        phoneNumber: '(604) 931-9045',
        google: 'No reviews and ratings',
        FHreport: 'N/A',
        FHreportUrl: 'https://www.healthspace.ca/clients/fha/FHA_Website.nsf/CCFL-FacilityHistory?OpenView&RestrictToCategory=465A1885729C0B1A88256D2700704DE8',
        image: 'https://maps.googleapis.com/maps/api/streetview?location=755+Adiron+Ave%2C+Coquitlam%2C+BC+V3J4K1&size=768x576&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=YoiLl5jM0Zmc7uo9HXAGJlCsEO0=',
    }
]

export default DAYCARE_DATA